version: "2"
services:
  db:
    image: postgres:9.5
    logging:
      driver: "none"
  redis:
    image: redis:3.2
    logging:
      driver: "none"
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - hbase
    environment:
      - DATABASE_URL=postgres://postgres@db/postgres
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1,
      - SECRET_KEY=59114b6a-2858-4caf-8878-482a24ee9542
      - CACHE_URL=redis://redis:6379/1
      - LOGGING_USE_JSON=1
      - HBASE_HOST=hbase
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - EXTRA_APPS=taar_api.hbase

    command:
      "web-dev"
  hbase:
    logging:
      driver: "none"
    build: ./docker/hbase
    ports:
      - "9090:9090"
    command:
      "/opt/run_hbase"